### ISSUE TITLE
你好，能提供数据吗？

### ISSUE THREAD

**Issue by zuowanbushiwo** [CharlesThaCat/echo-cancellation#1]
最近开始接触回声消除，打算好好学习你这个项目，运行您的程序时没有数据，能提供一下吗？我看好多源文件都引用这个数据：After reading Chapter 4 -- Subband Adaptive Filtering\room1_2m_pb\001_2mplayback_1646-802.wav
 这个数据在哪里可以获得？

**Comment by CharlesThaCat** [comment]
非常感谢你对项目的关注！
非常抱歉，因为音频数据是公司录制和提供的，因此不对外公开。
该音频数据只是包含“无回声纯音乐”与“人声唤醒词夹杂有回声音乐”的多音轨文件，相信你自己录制的话，应该实现难度也不大。

**Comment by zuowanbushiwo** [comment]
谢谢！
